import React, { useState } from 'react';
import { Recipe, LocalProfile } from '../types';
import { ChefHat, Plus, Flame, Clock, Star, Play, Sparkles, Edit3, Trash2, Share2, Bookmark, Check } from 'lucide-react';
import { getProfile } from '../utils/storage';
import { shareRecipe } from '../services/share';

interface MyRecipesViewProps {
  profile?: LocalProfile;
  recipes: Recipe[];
  onSelectRecipe: (recipe: Recipe) => void;
  onStartCooking: (recipe: Recipe, e?: React.MouseEvent) => void;
  onOpenCreateRecipe: () => void;
  onEditProfile?: () => void;
  onEditRecipe?: (recipe: Recipe) => void;
  onDeleteRecipe?: (recipeId: string, recipeTitle: string) => void;
}

export const MyRecipesView: React.FC<MyRecipesViewProps> = ({
  profile: propProfile,
  recipes,
  onSelectRecipe,
  onStartCooking,
  onOpenCreateRecipe,
  onEditProfile,
  onEditRecipe,
  onDeleteRecipe,
}) => {
  const profile: LocalProfile = propProfile || getProfile();
  const [copiedId, setCopiedId] = useState<string | null>(null);

  // Filter recipes owned or generated by user
  const userRecipes = recipes.filter(
    (r) =>
      r.author?.name?.toLowerCase().includes('you') ||
      r.author?.name === profile.name ||
      r.id.startsWith('user-rec-') ||
      r.isAiGenerated
  );

  const handleShare = async (e: React.MouseEvent, recipe: Recipe) => {
    e.stopPropagation();
    const res = await shareRecipe(recipe);
    if (res.copied) {
      setCopiedId(recipe.id);
      setTimeout(() => setCopiedId(null), 2500);
    }
  };

  return (
    <div className="space-y-8 pb-16 animate-in fade-in duration-200">
      {/* Profile Header Banner */}
      <div className="rounded-3xl bg-gradient-to-r from-[#fef1ea] via-white to-[#f8ece5] border border-[#e1bfb2]/40 p-6 sm:p-8 flex flex-col sm:flex-row items-center sm:items-start justify-between gap-6 shadow-xs">
        <div className="flex flex-col sm:flex-row items-center gap-5 text-center sm:text-left">
          <div className="w-20 h-20 sm:w-24 sm:h-24 rounded-3xl bg-gradient-to-tr from-[#ffdbcd] to-[#ffdcc4] text-[#9f3d00] font-serif font-bold text-3xl flex items-center justify-center shrink-0 shadow-md ring-4 ring-white">
            {(profile?.name || 'Chef')
              .split(' ')
              .filter(Boolean)
              .map((n) => n.charAt(0))
              .join('')
              .slice(0, 2)
              .toUpperCase() || 'CH'}
          </div>

          <div>
            <div className="inline-flex items-center gap-1.5 px-3 py-0.5 rounded-full bg-[#ffdbcd] text-[#9f3d00] text-xs font-bold mb-1.5">
              <Sparkles className="w-3.5 h-3.5" />
              <span>{profile.cookingLevel || 'Master Home Gastronomist'}</span>
            </div>
            <h1 className="font-serif text-2xl sm:text-3xl font-bold text-[#201a17]">
              {profile.name || 'Chef Studio'}
            </h1>
            <p className="text-xs sm:text-sm text-[#594137] max-w-md mt-0.5">
              {profile.bio || 'Culinary creator experimenting with bespoke recipes and Gemini AI flavor pairings.'}
            </p>

            <div className="flex items-center justify-center sm:justify-start gap-4 mt-3 text-xs text-[#594137]">
              <span>
                <strong className="text-[#201a17]">{userRecipes.length}</strong> Recipes
              </span>
              <span>•</span>
              <span>
                <strong className="text-[#201a17]">{profile.savedRecipes?.length || 0}</strong> Bookmarked
              </span>
              <span>•</span>
              <span>
                <strong className="text-[#201a17]">4.9</strong> Chef Rating
              </span>
            </div>
          </div>
        </div>

        <div className="flex items-center gap-2.5 shrink-0 flex-wrap sm:flex-nowrap">
          {onEditProfile && (
            <button
              onClick={onEditProfile}
              className="inline-flex items-center gap-1.5 px-3.5 py-3 rounded-xl border border-[#e1bfb2] hover:bg-[#fff5f0] text-[#9f3d00] font-bold text-xs shadow-xs transition-all cursor-pointer"
            >
              <Edit3 className="w-4 h-4" />
              <span>Edit Chef Details</span>
            </button>
          )}

          <button
            onClick={onOpenCreateRecipe}
            className="inline-flex items-center gap-2 px-5 py-3 rounded-xl bg-[#9f3d00] hover:bg-[#c74e00] text-white font-bold text-xs shadow-md transition-all cursor-pointer"
          >
            <Plus className="w-4 h-4" />
            <span>Create New Recipe</span>
          </button>
        </div>
      </div>

      {/* Recipe Grid */}
      <div>
        {userRecipes.length === 0 ? (
          <div className="text-center py-16 px-4 bg-white rounded-3xl border border-dashed border-[#e1bfb2] space-y-3">
            <ChefHat className="w-12 h-12 text-[#9f3d00]/40 mx-auto" />
            <h3 className="font-serif font-bold text-[#201a17] text-lg">No recipes created yet</h3>
            <p className="text-xs text-[#594137] max-w-sm mx-auto">
              Create your own custom dish or tap the AI Kitchen to craft a new signature meal!
            </p>
            <button
              onClick={onOpenCreateRecipe}
              className="inline-flex items-center gap-1.5 px-4 py-2.5 rounded-xl bg-[#9f3d00] text-white text-xs font-semibold hover:bg-[#c74e00] transition-all cursor-pointer"
            >
              <Plus className="w-4 h-4" />
              <span>Create Recipe Now</span>
            </button>
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
            {userRecipes.map((recipe) => (
              <div
                key={recipe.id}
                onClick={() => onSelectRecipe(recipe)}
                className="group bg-white rounded-2xl border border-[#e1bfb2]/40 overflow-hidden shadow-xs hover:shadow-lg transition-all duration-300 flex flex-col cursor-pointer hover:-translate-y-1"
              >
                {/* Image + Quick overlay actions */}
                <div className="relative aspect-4/3 overflow-hidden bg-[#f8ece5]">
                  <img
                    src={recipe.imageUrl}
                    alt={recipe.title}
                    className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                  />

                  {/* Top tags */}
                  <div className="absolute top-2.5 left-2.5 flex flex-wrap gap-1">
                    {recipe.isAiGenerated && (
                      <span className="px-2 py-0.5 rounded-full bg-purple-600/90 text-white text-[10px] font-bold backdrop-blur-xs flex items-center gap-1 shadow-xs">
                        <Sparkles className="w-3 h-3" /> AI
                      </span>
                    )}
                    <span className="px-2 py-0.5 rounded-full bg-black/60 text-white text-[10px] font-bold backdrop-blur-xs">
                      {recipe.cuisine}
                    </span>
                  </div>

                  {/* Action Bar Overlay */}
                  <div className="absolute top-2.5 right-2.5 flex items-center gap-1 opacity-90 group-hover:opacity-100 transition-opacity">
                    <button
                      type="button"
                      title="Share Recipe"
                      onClick={(e) => handleShare(e, recipe)}
                      className="p-1.5 rounded-full bg-white/90 hover:bg-white text-gray-700 hover:text-[#9f3d00] shadow-sm transition-transform cursor-pointer"
                    >
                      {copiedId === recipe.id ? (
                        <Check className="w-3.5 h-3.5 text-emerald-600" />
                      ) : (
                        <Share2 className="w-3.5 h-3.5" />
                      )}
                    </button>

                    {onEditRecipe && (
                      <button
                        type="button"
                        title="Edit Recipe"
                        onClick={(e) => {
                          e.stopPropagation();
                          onEditRecipe(recipe);
                        }}
                        className="p-1.5 rounded-full bg-white/90 hover:bg-white text-gray-700 hover:text-[#9f3d00] shadow-sm transition-transform cursor-pointer"
                      >
                        <Edit3 className="w-3.5 h-3.5" />
                      </button>
                    )}

                    {onDeleteRecipe && (
                      <button
                        type="button"
                        title="Delete Recipe"
                        onClick={(e) => {
                          e.stopPropagation();
                          onDeleteRecipe(recipe.id, recipe.title);
                        }}
                        className="p-1.5 rounded-full bg-white/90 hover:bg-white text-gray-700 hover:text-rose-600 shadow-sm transition-transform cursor-pointer"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    )}
                  </div>

                  {/* Cooking Mode Floating Button */}
                  <button
                    type="button"
                    onClick={(e) => onStartCooking(recipe, e)}
                    className="absolute bottom-2.5 right-2.5 px-3 py-1.5 rounded-xl bg-[#9f3d00] hover:bg-[#c74e00] text-white text-[11px] font-bold shadow-md flex items-center gap-1.5 backdrop-blur-xs transition-transform active:scale-95 cursor-pointer"
                  >
                    <Play className="w-3 h-3 fill-white" />
                    <span>Cook</span>
                  </button>
                </div>

                {/* Content */}
                <div className="p-4 flex flex-col flex-1 justify-between gap-3">
                  <div>
                    <h3 className="font-serif font-bold text-base text-[#201a17] group-hover:text-[#9f3d00] transition-colors line-clamp-1">
                      {recipe.title}
                    </h3>
                    <p className="text-xs text-[#594137] line-clamp-2 mt-1">
                      {recipe.description}
                    </p>
                  </div>

                  <div className="flex items-center justify-between text-xs text-[#594137] pt-2 border-t border-gray-100">
                    <span className="flex items-center gap-1">
                      <Clock className="w-3.5 h-3.5 text-[#9f3d00]" />
                      <span>{recipe.prepTimeMinutes + recipe.cookTimeMinutes}m</span>
                    </span>
                    <span className="flex items-center gap-1">
                      <Flame className="w-3.5 h-3.5 text-amber-600" />
                      <span>{recipe.nutrition?.calories || 400} kcal</span>
                    </span>
                    <span className="flex items-center gap-1 text-amber-600 font-bold">
                      <Star className="w-3.5 h-3.5 fill-amber-500 text-amber-500" />
                      <span>{recipe.rating}</span>
                    </span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};
